# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kneece Investigations, LLC
email: about@kneeceinv.com
description: > # this means to ignore newlines until "baseurl:"
  Providing both Investigative Services and Security Officers
domain: jonnalley.github.io
baseurl: "/kneecesite" # the subpath of your site, e.g. /blog
url: "https://jonnalley.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: Kneece Investigations, LLC
address_line: 113 West Eutaw Street, Saluda, SC 29138
telephone_number: 864.445.3713
fax_number: 864.445.0300
company_email: about@kneeceinv.com
google_map: ""

# Social Link
facebook_link: ""
twitter_link: ""
linkedin_link: ""
googleplus_link: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
